"use client";
import {useEffect,useMemo,useRef,useState} from"react";
type Level="P1"|"P2"|"P3";type Priority={level:Level;score:number;label:string;reason:string;focus_tags:string[]};type Knowledge={vocabulary:{term:string;meaning:string}[];collocations:{phrase:string;meaning:string}[]};type Item={id:number;question?:string;question_translation?:string;choices:string[];answer:string;answer_explain?:string;question_type?:string;evidence?:string;strategy?:string;response_style?:string;choice_translations?:string[];grammar_point?:string;knowledge_accumulation?:Knowledge;priority?:Priority};
type Group={id:string|number;set_title?:string;question?:string;question_translation?:string;choices?:string[];choice_translations?:string[];answer?:string;answer_explain?:string;audio_path?:string;picture_path?:string;passage?:string;transcript?:string;transcript_translation?:string;passage_translation?:string;topic?:string;items?:Item[];priority?:Priority};
type Part={part:number;part_name:string;section_type:string;questions:Group[]};type Bank={name:string;parts:Part[];priority_methodology?:{levels:Record<Level,string>;disclaimer:string;part5_note:string}};type Saved={answers:Record<string,string>;wrong:number[];stars:number[]};type Filter="ALL"|Level;
const L=["A","B","C","D"],P=(x?:string)=>x?`bank/${x}`:"",LEVELS:Filter[]=["ALL","P1","P2","P3"],LABELS:Record<Filter,string>={ALL:"全部",P1:"P1 必刷",P2:"P2 重点",P3:"P3 巩固"};
export default function Home(){const[bank,setBank]=useState<Bank|null>(null),[part,setPart]=useState(1),[gi,setGi]=useState(0),[filter,setFilter]=useState<Filter>("ALL"),[priorityOrder,setPriorityOrder]=useState(true),[show,setShow]=useState<Record<number,boolean>>({}),[analysis,setAnalysis]=useState(false),[text,setText]=useState(false),[translation,setTranslation]=useState(false),[side,setSide]=useState(false);const[saved,setSaved]=useState<Saved>({answers:{},wrong:[],stars:[]});const audio=useRef<HTMLAudioElement>(null);
useEffect(()=>{fetch("bank/question.json").then(r=>r.json()).then(setBank);const s=localStorage.getItem("toeic-progress-v2");if(s)setSaved(JSON.parse(s))},[]);useEffect(()=>{if(bank)localStorage.setItem("toeic-progress-v2",JSON.stringify(saved))},[saved,bank]);
const p=bank?.parts.find(x=>x.part===part),rawGroups=p?.questions||[],groups=useMemo(()=>{const selected=filter==="ALL"?rawGroups:rawGroups.filter(x=>x.priority?.level===filter);return priorityOrder?[...selected].sort((a,b)=>(a.priority?.level||"P3").localeCompare(b.priority?.level||"P3")||String(a.id).localeCompare(String(b.id),undefined,{numeric:true})):selected},[rawGroups,filter,priorityOrder]),g=groups[gi],items:Item[]=g?(g.items||[{...g,id:+g.id,question:g.question,choices:g.choices||[],answer:g.answer||"",answer_explain:g.answer_explain} as Item]):[];const done=Object.keys(saved.answers).length;
const resetView=()=>{setGi(0);setShow({});setAnalysis(false);setText(false);setTranslation(false)};const go=(n:number)=>{setGi(Math.max(0,Math.min(groups.length-1,n)));setShow({});setAnalysis(false);setText(false);setTranslation(false);scrollTo({top:0,behavior:"smooth"})};const choose=(q:Item,l:string)=>{const ok=l===q.answer;setSaved(s=>({...s,answers:{...s.answers,[q.id]:l},wrong:ok?s.wrong.filter(x=>x!==q.id):[...new Set([...s.wrong,q.id])]}));setShow(s=>({...s,[q.id]:true}))};
useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==="ArrowRight")go(gi+1);if(e.key==="ArrowLeft")go(gi-1);if(e.key===" "){e.preventDefault();audio.current?.paused?audio.current.play():audio.current?.pause()}};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn)});
if(!bank)return <main className="loading"><div className="loader"/>正在载入题库…</main>;
const listening=part<=4,hidden=part<=2,asSet=part>=3,range=["1–6","7–31","32–70","71–100","101–130","131–146","147–200"][part-1];return <main className="shell"><header><button className="menu" onClick={()=>setSide(!side)}>☰</button><div className="brand"><span className="mark">T</span><div><b>TOEIC SPRINT</b><small>Official 11 · Test 1</small></div></div><div className="headerProgress"><span>{done} / 200</span><div><i style={{width:`${done/2}%`}}/></div><b>{Math.round(done/2)}%</b></div></header><div className="layout"><aside className={side?"open":""}><div className="asideTitle">优先级刷题</div><div className="priorityFilters">{LEVELS.map(x=><button key={x} className={filter===x?"on":""} onClick={()=>{setFilter(x);resetView()}}>{LABELS[x]}</button>)}</div><div className="priorityLegend"><p><b className="badge p1">P1</b> 高频核心 · 优先必刷</p><p><b className="badge p2">P2</b> 重点题型 · 稳定巩固</p><p><b className="badge p3">P3</b> 基础覆盖 · 查漏补缺</p></div><div className="asideTitle partsTitle">练习目录</div>{bank.parts.map(x=>{const count=(l:Level)=>x.questions.filter(q=>q.priority?.level===l).length;return <button className={part===x.part?"part active":"part"} key={x.part} onClick={()=>{setPart(x.part);setSide(false);resetView()}}><span className="partNo">{x.part}</span><span><b>Part {x.part} <i className={x.part<=4?"tag listen":"tag read"}>{x.part<=4?"听力":"阅读"}</i></b><small>{x.part_name} · {["1–6","7–31","32–70","71–100","101–130","131–146","147–200"][x.part-1]}</small><em>P1 {count("P1")} · P2 {count("P2")} · P3 {count("P3")}</em></span></button>})}</aside><section className="content"><div className="topline"><div><span className="eyebrow">{listening?"LISTENING":"READING"} · PART {part}</span><h1>{p?.part_name}</h1></div><div className="topTools"><button className={priorityOrder?"orderBtn on":"orderBtn"} onClick={()=>{setPriorityOrder(!priorityOrder);resetView()}}>{priorityOrder?"优先级顺序":"原题顺序"}</button><div className="groupCount">第 {groups.length?gi+1:0} / {groups.length} {asSet?"套":"题"}</div></div></div>{!g?<div className="empty"><b>当前 Part 没有 {LABELS[filter]} 题目</b><p>换一个优先级即可继续训练。</p><button onClick={()=>{setFilter("ALL");resetView()}}>查看全部</button></div>:<><div className="setRail" aria-label="套题导航">{groups.map((x,i)=><button key={x.id} className={i===gi?"current":""} onClick={()=>go(i)}><span>{x.id}</span>{x.priority&&<PriorityBadge value={x.priority}/>}</button>)}</div><div className="questionNav"><span>题号 <b>{g.id}</b></span><div className="miniProgress"><i style={{width:`${(gi+1)/groups.length*100}%`}}/></div><span>{range}</span></div>{g.priority&&<div className="priorityBrief"><PriorityBadge value={g.priority}/><div><b>{g.set_title||g.priority.label}</b><p>{g.priority.reason}</p><div>{g.priority.focus_tags.map(x=><span key={x}>{x}</span>)}</div></div></div>}<article>
{listening&&g.audio_path&&<div className="audio"><button className="playBtn" onClick={()=>audio.current?.paused?audio.current.play():audio.current?.pause()}>▶</button><div className="audioLabel"><b>听力音频</b><small>空格键暂停 / 继续</small></div><audio ref={audio} controls src={P(g.audio_path)}/><div className="audioActions"><button className="translateBtn" onClick={()=>setText(!text)}>{text?"隐藏原文":"查看原文"}</button><button className="analysisBtn" onClick={()=>setAnalysis(!analysis)}>{analysis?"隐藏解析":"查看解析"}</button></div></div>}
{listening&&part!==1&&text&&<div className="transcript listeningTranscript"><pre>{part===2?`${g.question}\n${g.choices?.map((x,i)=>`${L[i]}. ${x}`).join("\n")}`:g.transcript}</pre><button className="translateBtn" onClick={()=>setTranslation(!translation)}>{translation?"隐藏中文":"翻译原文"}</button>{translation&&<div className="translation">{g.transcript_translation}</div>}</div>}
{part===1&&g.picture_path&&<div className={text?"part1Material withTranscript":"part1Material"}><div className="images"><img src={P(g.picture_path)} alt="照片描述题"/></div>{text&&<div className="transcript"><pre>{g.choices?.map((x,i)=>`${L[i]}. ${x}`).join("\n")}</pre><button className="translateBtn" onClick={()=>setTranslation(!translation)}>{translation?"隐藏中文":"翻译原文"}</button>{translation&&<div className="translation">{g.transcript_translation}</div>}</div>}</div>}
{part>=5&&g.passage&&<><div className={part===6?"passage cloze":"passage"}>{part===6?markCloze(g.passage):g.passage}</div><div className="actionRow"><button className="translateBtn" onClick={()=>setTranslation(!translation)}>{translation?"隐藏中文":"翻译原文"}</button><button className="analysisBtn" onClick={()=>setAnalysis(!analysis)}>{analysis?"隐藏解析":"查看解析"}</button></div>{translation&&<div className="translation">{g.passage_translation}</div>}</>}
{items.map(q=><QuestionBlock key={q.id} q={q} part={part} hidden={hidden} group={g} shown={!!show[q.id]} reveal={analysis} chosen={saved.answers[q.id]} choose={choose}/>) }
{part===5&&<div className="textTools"><button className="analysisBtn" onClick={()=>setAnalysis(!analysis)}>{analysis?"隐藏解析":"查看解析"}</button></div>}
</article><div className="bottom"><button disabled={gi===0} onClick={()=>go(gi-1)}>← 上一{asSet?"套":"题"}</button><button disabled={gi===groups.length-1} onClick={()=>go(gi+1)}>下一{asSet?"套":"题"} →</button></div></>}</section></div></main>}

function QuestionBlock({q,part,hidden,group:_,shown,reveal,chosen,choose}:{q:Item;part:number;hidden:boolean;group:Group;shown:boolean;reveal:boolean;chosen?:string;choose:(q:Item,l:string)=>void}){const[translated,setTranslated]=useState(false);return <div className="questionBlock"><div className="itemHeading">{q.priority&&<PriorityBadge value={q.priority}/>}<span>{q.priority?.label}</span></div>{!hidden&&q.question&&<><h2><span>{q.id}.</span> {q.question}</h2>{part===5&&<><button className="translateBtn" onClick={()=>setTranslated(!translated)}>{translated?"隐藏中文":"翻译题干"}</button>{translated&&<div className="translation">{q.question_translation}</div>}</>}</>}<div className={hidden?"choices examHidden":"choices"}>{q.choices.map((c,i)=>{const l=L[i],state=reveal&&l===q.answer?"correct":shown&&chosen===l?(chosen===q.answer?"correct":"incorrect"):"";return <button className={state} key={l} onClick={()=>choose(q,l)}><span>{l}</span>{!hidden&&<p>{c}</p>}{state==="correct"&&<b>✓</b>}{state==="incorrect"&&<b>×</b>}</button>})}</div>{reveal&&<div className={chosen===q.answer?"explain good":"explain bad"}><div><b>答案：{q.answer} · {q.question_type}</b></div>{part===2&&<p><strong>回答方式：</strong>{q.response_style}</p>}{q.grammar_point&&<p><strong>考查知识点：</strong>{q.grammar_point}</p>}<p><strong>解题思路：</strong>{q.strategy}</p>{part>=3&&<p><strong>原文定位：</strong>{q.evidence}</p>}<p><strong>解析：</strong>{q.answer_explain}</p>{part>=3&&<div className="optionZh"><strong>选项释义：</strong>{q.choice_translations?.map((z,i)=><p key={i}>{z}</p>)}</div>}{q.knowledge_accumulation&&<KnowledgeCard value={q.knowledge_accumulation}/>}</div>}</div>}
function PriorityBadge({value}:{value:Priority}){return <b className={`badge ${value.level.toLowerCase()}`} title={`训练优先级 ${value.level} · ${value.score} 分`}>{value.level}</b>}
function KnowledgeCard({value}:{value:Knowledge}){return <section className="knowledge"><div className="knowledgeTitle"><span>✦</span><div><b>知识积累</b><small>Vocabulary & Collocations</small></div></div><div className="knowledgeGrid"><div><h3>重点单词</h3>{value.vocabulary.map((x,i)=><p key={`${x.term}-${i}`}><strong>{x.term}</strong><span>{x.meaning}</span></p>)}</div><div><h3>重点短语与搭配</h3>{value.collocations.map((x,i)=><p key={`${x.phrase}-${i}`}><strong>{x.phrase}</strong><span>{x.meaning}</span></p>)}</div></div></section>}
function markCloze(value:string){return value.replace(/[“\"]?\b(1(?:3[1-9]|4[0-6]))\b\.?/g,"【$1】 ______ ")}
